spring:
  application:
    name: financial-service
  jpa:
    hibernate:
      ddl-auto: create
#  config:
#    import: 'optional:configserver:http://localhost:8088'
resilience4j:
  retry:
    instances:
      ledgerRetry:
        max-attempts: 3
        wait-duration: 50ms
        retry-exceptions:
          - jakarta.persistence.OptimisticLockException
eureka:
  client:
    enabled: false

